language: bash


os: linux

services: docker

dist: bionic

arch: 
 - ppc64le
 - amd64
 - s390x

jobs:
  include:

   - stage: building multi-arch image
     arch: amd64
     script: chmod +x ./create-multi-arch.sh; ./create-multi-arch.sh
